language: generic

services:
  - docker

before_install:
  - docker build -t phade160/fpl_server .
  - docker build -t phade160/fpl_client ./frontend

# script: docker run
#   -e "POSTGRES_HOST=$POSTGRES_HOST"
#   -e "POSTGRES_USER=$POSTGRES_USER"
#   -e "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
#   -e "POSTGRES_DB=$POSTGRES_DB"
#   -e "POSTGRES_PORT=$POSTGRES_PORT"
#   phade160/fpl_app

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  - docker push phade160/fpl_app
