wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    code_path: code/fpl_engineering/train.py
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.15
    start_time: 1668658998.574122
    t:
      1:
        - 1
        - 2
        - 3
        - 9
        - 11
        - 12
        - 40
        - 41
        - 49
        - 55
      2:
        - 1
        - 2
        - 3
        - 9
        - 11
        - 12
        - 40
        - 41
        - 49
        - 55
      3:
        - 2
        - 16
        - 23
      4: 3.7.15
      5: 0.13.5
      6: 4.24.0
      8:
        - 5
batch_size:
  desc: null
  value: 256
data_dir:
  desc: null
  value: data
dropout:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 200
hidden_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.0001
lr:
  desc: null
  value: 0.0001
n_features:
  desc: null
  value: 35
n_layers:
  desc: null
  value: 2
num_layers:
  desc: null
  value: 2
seq_len:
  desc: null
  value: 5
