version: "3.9"

services:
  client:
    build: ./frontend
    ports:
      - 5173:3000
    volumes:
      - ./frontend:/user/src/app
      - /user/src/app/node_modules/
    depends_on:
      - server
    env_file:
      - ./frontend/.env

  server:
    build: ./
    env_file:
      - ./.env

    ports:
      - 5100:5100
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    ports:
      - 5431:5432
    env_file:
      - ./.env

    volumes:
      - db-fantasy:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

volumes:
  db-fantasy:
