services:
  database:
    image: postgres
    restart: always
    ports:
      - 5431:5432
    env_file:
      - ./.env

    volumes:
      - db-fantasy:/var/lib/postgresql/data

  app:
    build: ./
    env_file:
      - ./.env

    ports:
      - 5110:5100
    depends_on:
      - database

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

volumes:
  db-fantasy:
